### ISSUE TITLE
Issue when file path has a number in dailyrotate.Newfile

### ISSUE THREAD

**Issue by ikenne** [kjk/dailyrotate#2]
If a the path name has number in it, with additional time format, e.g.
```
path := "/home/foo/go-2/src/api/log"
timeFormat := "Trace 2006-01-02.txt"
pathFormat := filepath.Join(path, timeFormat)
f, err := dailyrotate.NewFile(pathFormat, onClose)
```
f.path has a value like "/home/foo/go-10/src/api/log/Trace 2009-11-10.txt" instead of 
"/home/foo/go-2/src/api/log/Trace 2009-11-10.txt"

The issue seems to be the application of the time.Format on the input pathFormat parameter. See [https://play.golang.org/p/vLnKsIAIsvA](https://play.golang.org/p/vLnKsIAIsvA)

Perhaps having an option to create the file with parameters for a directory path and the file name format, something like:
```
dailyrotate.NewFile(path, timeFormat, onClose)
```
the code would apply the time.Format to the timeFormat input, and the result joined to path.

**Comment by kjk** [comment]
Thanks for pointing it out.

Having a unique directory for each day seems like a valid use case so I've added `NewFileWithPathGenerator` where one has full control over generating a path for the log file by providing a function that recieves a time for which to generate a path and returns the path.

I've also documented this pitfall in the docs.
